task:
  name: "Build ROM"
  timeout_in: 6h 
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32
  
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - git config --global user.name "RON1N9"
       - git config --global user.email linuxxxkali33@gmail.com
  SyncROM_script:
       - git clone https://github.com/akhilnarang/script
       - cd scripts
       - bash setup/android_build_env.sh
       - git clone https://github.com/Rahat87942R/local_manifest.git --depth 1 -b master .repo/local_manifests 
       - cd ..
       - repo init -u https://github.com/crdroidandroid/android.git -b 11.0
       - repo sync
  CloneDT_script:
       - git clone https://github.com/RON1N9/android_device_samsung_j7elte device/samsung/j7elte -b Crdroid-11
       - git clone https://github.com/Techy0302/android_device_samsung_universal7580-common device/samsung/universal7580-common
       - git clone https://github.com/FlominatorGD/proprietary_vendor_samsung vendor/samsung
       - git clone https://github.com/maxx0021/android_kernel_samsung_universal7580 kernel/samsung/universal7580
       - git clone https://github.com/maxx0021/android_hardware_samsung_slsi_exynos hardware/samsung_slsi/exynos
       - git clone https://github.com/maxx0021/android_hardware_samsung_slsi_exynos7580 hardware/samsung_slsi/exynos7580
       - git clone https://github.com/maxx0021/android_hardware_samsung_slsi_openmax hardware/samsung_slsi/openmax
       - git clone https://github.com/maxx0021/android_hardware_samsung_slsi_exynos5 hardware/samsung_slsi/exynos5
       - git clone https://github.com/FlominatorGD/android_hardware_samsung hardware/samsung
  Build_script:
       - source build/envsetup.sh
       - lunch lineage_j7elte-userdebug
       - brunch lineage_j7elte-userdebug
      
